name: Playwright Cucumber Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: List current directory
        run: ls -la

      - name: Set npm registry
        run: npm config set registry https://registry.npmjs.org/
      
      - name: Clear npm cache
        run: npm cache clean --force
      
      - name: Move to Playwright Cucumber Project and Install Cucumber Dependencies explicit
        run: |
          if [ -d "playwright-cucumber-project" ]; then
            cd playwright-cucumber-project
            echo "Now inside: $(pwd)"
            ls -la
            npm install @cucumber/cucumber --save-dev
          else
            echo "Directory 'playwright-cucumber-project' not found!"
            exit 1
          fi
      
      - name: Install other dependencies
        run: npm install
      
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Cucumber Tests
        run: npx cucumber-js

      - name: Upload JSON Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-json-report
          path: playwright-cucumber-project/reports/cucumber-report.json
          retention-days: 7

      - name: Generate HTML Report
        if: always()
        run: npm run report

      - name: Upload HTML Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: reports/cucumber-report.html
          retention-days: 7
